### ISSUE TITLE
chunks not always filling edges

### ISSUE THREAD

**Issue by XeonG** [richardbiely/Voxelmetric#25] opened 2016-07-24 22:03 UTC
Just setting a large area with air.. left one of the sides completely empty.. (I think) it was on the chunk edge.. just grabbed a video of it to show..

https://videobin.org/+dij/h8c.html  (I put a few holes in the side of it before capturing it) 

also have noticed the classic mc error with chunks not always loading/showing up when in view, not sure why that occurs guess never get away from that.

**Comment by richardbiely** [comment] 2016-07-31 06:06
It's actually caused by an optimization of geometry generation - Voxe tries to build geometry only for the top layer of chunks. This speeds things up a lot, however, does not work properly if not done taking chunk neighbors into account...
Because I want to have something stable, I'll remove the optimization for 0.1. I would have done so anyway later, because the geometry is going to be generated completely differently soon.

Fixed in: cf8b7852123a708c50a2f84a1fe1d79a9ff98e79

Performance can suffer for now.

**Closed as completed by richardbiely** 2016-07-31 06:06 UTC
Labels: bug
